/*  YEAR WISE SALES OF EV-VEHICLES (2-WHEELER, 4-WHEELERS ) */
select * from sales_by_states;

WITH Wheelers_2 AS (
SELECT YEAR(DATES) AS YEARS, SUM(ELECTRIC_VEHICLES_SOLD) Wheelers_2_SALES
FROM SALES_BY_STATES 
WHERE VEHICLE_CATEGORY = "2-Wheelers"
GROUP BY YEARS 
),
Wheelers_4 AS (
SELECT YEAR(DATES) AS YEARS, SUM(ELECTRIC_VEHICLES_SOLD) Wheelers_4_SALES 
FROM SALES_BY_STATES 
WHERE VEHICLE_CATEGORY = "4-Wheelers"
GROUP BY YEARS
)
SELECT W2.YEARS, W2.Wheelers_2_SALES, W4.Wheelers_4_SALES 
FROM Wheelers_2 W2 INNER JOIN Wheelers_4 W4
ON W2.YEARS = W4.YEARS;
