/* TOTAL SALES OF 2 WHEELERS AND 4 WHEELERS */

SELECT * FROM sales_by_states;
select * from sales_by_makers;

SELECT SUM(ELECTRIC_VEHICLES_SOLD) AS TOTAL_EV_SALES_IN_2_WHEELER FROM SALES_BY_STATES 
WHERE VEHICLE_CATEGORY = '2-Wheelers';


SELECT SUM(ELECTRIC_VEHICLES_SOLD) AS TOTAL_EV_SALES_IN_4_WHEELER FROM SALES_BY_STATES 
WHERE VEHICLE_CATEGORY = '4-Wheelers';